name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            role-session-name: github-actions
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload to S3
        run: aws s3 sync out/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --cache-control "no-cache"

